# Generated by Django 5.1.4 on 2026-05-13 07:31

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('general', 'Общее'), ('investment', 'Инвестирование'), ('payment', 'Платежи'), ('account', 'Учётная запись'), ('security', 'Безопасность')], default='general', max_length=20)),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField()),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Вопрос FAQ',
                'verbose_name_plural': 'FAQ',
                'ordering': ['category', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('investor', 'Инвестор'), ('entrepreneur', 'Предприниматель'), ('admin', 'Администратор')], default='investor', max_length=16)),
                ('last_name_ru', models.CharField(blank=True, max_length=64, verbose_name='Фамилия')),
                ('first_name_ru', models.CharField(blank=True, max_length=64, verbose_name='Имя')),
                ('middle_name_ru', models.CharField(blank=True, max_length=64, verbose_name='Отчество')),
                ('inn', models.CharField(blank=True, max_length=12, verbose_name='ИНН')),
                ('passport', models.CharField(blank=True, max_length=32, verbose_name='Паспорт')),
                ('phone', models.CharField(blank=True, max_length=24, verbose_name='Телефон')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/')),
                ('esia_uid', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Идентификатор ЕСИА')),
                ('registered_via_esia', models.BooleanField(default=False, verbose_name='Зарегистрирован через ЕСИА')),
                ('e_signature_status', models.CharField(choices=[('none', 'Не оформлена'), ('pending', 'На проверке'), ('verified', 'Подтверждена')], default='none', max_length=16)),
                ('verification_status', models.CharField(choices=[('not_verified', 'Не подтверждён'), ('pending', 'На проверке'), ('verified_esia', 'Подтверждён через Госуслуги'), ('verified_manual', 'Подтверждён вручную')], default='not_verified', max_length=20)),
                ('api_token', models.CharField(blank=True, max_length=64, unique=True, verbose_name='API-токен')),
                ('two_factor_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('share_percent', models.DecimalField(decimal_places=4, max_digits=6)),
                ('risk_at_purchase', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий')], max_length=8)),
                ('risk_disclaimer_accepted', models.BooleanField(default=False)),
                ('signature_hash', models.CharField(blank=True, max_length=64)),
                ('escrow_account', models.CharField(blank=True, max_length=32)),
                ('is_sold', models.BooleanField(default=False, verbose_name='Доля продана')),
                ('sold_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Инвестиция',
                'verbose_name_plural': 'Инвестиции',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DividendPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('paid_at', models.DateTimeField()),
                ('is_paid', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, max_length=256)),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='core.investment')),
            ],
            options={
                'ordering': ['paid_at'],
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Баланс')),
                ('invested', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Вложено')),
                ('dividends', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Дивиденды')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Портфель',
                'verbose_name_plural': 'Портфели',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('slogan', models.CharField(blank=True, max_length=256, verbose_name='Слоган')),
                ('description', models.TextField(verbose_name='Краткое описание')),
                ('full_content', models.TextField(blank=True, verbose_name='Подробное содержание (HTML)')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='projects/%Y/%m/', verbose_name='Обложка')),
                ('industry', models.CharField(choices=[('it', 'IT и технологии'), ('fintech', 'Финтех'), ('healthcare', 'Здравоохранение'), ('education', 'Образование'), ('ecology', 'Экология'), ('manufacturing', 'Производство'), ('retail', 'Ритейл'), ('tourism', 'Туризм')], max_length=20)),
                ('type', models.CharField(choices=[('startup', 'Стартап'), ('expanding', 'Расширяющийся бизнес'), ('mature', 'Зрелая компания'), ('crowdfunding', 'Краудфандинг'), ('traditional', 'Традиционный бизнес')], max_length=20)),
                ('geography', models.CharField(blank=True, max_length=64, verbose_name='География')),
                ('goal', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Цель сбора')),
                ('raised', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Собрано')),
                ('min_investment', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Минимум')),
                ('expected_return', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Доходность %')),
                ('payback_years', models.PositiveSmallIntegerField(default=3, verbose_name='Окупаемость (лет)')),
                ('closing_date', models.DateField(blank=True, null=True, verbose_name='Дата закрытия')),
                ('risk', models.CharField(blank=True, choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий')], max_length=8)),
                ('attractiveness', models.CharField(blank=True, choices=[('low', 'Низкая'), ('medium', 'Средняя'), ('high', 'Высокая')], max_length=8)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('pending', 'На модерации'), ('active', 'Активный'), ('rejected', 'Отклонён'), ('closed', 'Закрыт')], default='pending', max_length=10)),
                ('promoted', models.BooleanField(default=False, verbose_name='В продвижении')),
                ('promotion_tier', models.CharField(blank=True, choices=[('', 'Без продвижения'), ('highlight', 'Подсветка карточки'), ('top', 'В топе витрины'), ('main', 'На главной')], default='', max_length=20)),
                ('promotion_until', models.DateTimeField(blank=True, null=True, verbose_name='Продвижение до')),
                ('moderation_comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_projects', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['-promoted', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('project_updated', 'Проект обновлён'), ('dividend', 'Дивиденды'), ('verification', 'Верификация'), ('support_reply', 'Ответ поддержки'), ('system', 'Системное'), ('promotion', 'Продвижение')], max_length=24)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('link_to', models.CharField(blank=True, max_length=200)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='core.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='investment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='investments', to='core.project'),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('type', models.CharField(choices=[('business_plan', 'Бизнес-план'), ('financial_model', 'Финансовая модель'), ('presentation', 'Презентация'), ('other', 'Прочее')], default='other', max_length=24)),
                ('file', models.FileField(upload_to='documents/%Y/%m/')),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=500, verbose_name='Краткое описание изменений')),
                ('details', models.JSONField(default=dict, verbose_name='Детали (что изменилось)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='core.project')),
            ],
            options={
                'verbose_name': 'Обновление проекта',
                'verbose_name_plural': 'Обновления проектов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, verbose_name='Тема')),
                ('category', models.CharField(choices=[('technical', 'Технический вопрос'), ('billing', 'Оплата и финансы'), ('account', 'Учётная запись'), ('project', 'Вопрос по проекту'), ('other', 'Прочее')], default='other', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Открыто'), ('answered', 'Отвечено'), ('closed', 'Закрыто')], default='open', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Обращение',
                'verbose_name_plural': 'Обращения',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('is_admin_reply', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_messages', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.supportticket')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('role', models.CharField(max_length=64)),
                ('bio', models.TextField(blank=True)),
                ('cv_file', models.FileField(blank=True, null=True, upload_to='cv/%Y/%m/', verbose_name='CV в PDF')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='core.project')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('deposit', 'Пополнение'), ('withdrawal', 'Вывод средств'), ('investment', 'Инвестирование'), ('dividend', 'Дивиденды'), ('sale', 'Продажа доли'), ('promotion', 'Покупка продвижения')], max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('pending', 'В обработке'), ('completed', 'Завершено'), ('failed', 'Ошибка')], default='pending', max_length=12)),
                ('escrow_account', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('investment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.investment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
